# Generated by Django 5.1.7 on 2025-03-09 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palmier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mouvementcaisse',
            options={'ordering': ['-date'], 'verbose_name': 'Mouvement de caisse', 'verbose_name_plural': 'Mouvements de caisse'},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['-date'], 'verbose_name': 'Opération', 'verbose_name_plural': 'Opérations'},
        ),
        migrations.AlterModelOptions(
            name='plantation',
            options={'ordering': ['nom'], 'verbose_name': 'Plantation', 'verbose_name_plural': 'Plantations'},
        ),
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ['-date_recolte'], 'verbose_name': 'Production', 'verbose_name_plural': 'Productions'},
        ),
        migrations.AlterModelOptions(
            name='vente',
            options={'ordering': ['-date_vente'], 'verbose_name': 'Vente', 'verbose_name_plural': 'Ventes'},
        ),
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='operation',
            name='cout',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='nombre_arbres',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='superficie',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='production',
            name='poids_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='production',
            name='quantite',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='vente',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='vente',
            name='quantite',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
