# Generated by Django 5.1.7 on 2025-03-09 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palmier', '0003_add_stock_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='stock_disponible',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vente',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
