services:
  - type: web
    name: palmaraie-bst
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd frontend && npm install && npm run build
    startCommand: gunicorn palmier.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://palmaraie-bst.onrender.com
      - key: REACT_APP_API_URL
        value: https://palmaraie-bst.onrender.com/api 